version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:326.0.0
    environment:
      GCLOUD_PROJECT: test2-mtlynch
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Retrieve client secret from CircleCI
          command: |
            echo "$GCP_CLIENT_SECRET" | \
              base64 --decode > "${HOME}/client-secret.json"
      - run:
          name: Authenticate gcloud
          command: |
            gcloud auth activate-service-account \
              --key-file "${HOME}/client-secret.json"
      - run:
          name: Configure gcloud project
          command: gcloud config set project "${GCLOUD_PROJECT}"
      - run:
          name: Deploy to AppEngine
          command: gcloud --quiet app deploy --promote app.yaml
workflows:
  version: 2
  test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
